services:
  server:
    build: ./server
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app
      - ./server/data:/app/data
    environment:
      - PKW_DB_URL=/app/data/test.sqlite
    restart: always

  client:
    build: ./client
    ports:
      - "8501:8501"
    volumes:
      - ./client/app:/app/app
    environment:
      - PKW_API_URL=http://server:8000/
    depends_on:
      - server
    restart: always
